### ISSUE TITLE
Credit card number with trailing space passed to CreditCard.valid_number? gives "TypeError: nil can't be coerced into Fixnum"

### ISSUE THREAD

**Issue by JasonBarnabe** [activemerchant/active_merchant#1783]
```ruby
2.0.0-p643 :001 > require 'activemerchant'
 => true 
2.0.0-p643 :002 > ActiveMerchant::Billing::CreditCard.valid_number?("1234567890123456")
 => false 
2.0.0-p643 :003 > ActiveMerchant::Billing::CreditCard.valid_number?("123456789012345")
 => false 
2.0.0-p643 :004 > ActiveMerchant::Billing::CreditCard.valid_number?("123456789012345 ")
TypeError: nil can't be coerced into Fixnum
	from /Users/jason/.rvm/gems/ruby-2.0.0-p643@test/gems/activemerchant-1.51.0/lib/active_merchant/billing/credit_card_methods.rb:183:in `+'
	from /Users/jason/.rvm/gems/ruby-2.0.0-p643@test/gems/activemerchant-1.51.0/lib/active_merchant/billing/credit_card_methods.rb:183:in `block in valid_checksum?'
	from /Users/jason/.rvm/gems/ruby-2.0.0-p643@test/gems/activemerchant-1.51.0/lib/active_merchant/billing/credit_card_methods.rb:180:in `each'
	from /Users/jason/.rvm/gems/ruby-2.0.0-p643@test/gems/activemerchant-1.51.0/lib/active_merchant/billing/credit_card_methods.rb:180:in `valid_checksum?'
	from /Users/jason/.rvm/gems/ruby-2.0.0-p643@test/gems/activemerchant-1.51.0/lib/active_merchant/billing/credit_card_methods.rb:71:in `valid_number?'
	from (irb):4
	from /Users/jason/.rvm/rubies/ruby-2.0.0-p643/bin/irb:12:in `<main>'
```
Should return `false`.

**Comment by girasquid** [comment]
As a temporary workaround for now, strip non-digits from your credit card numbers.

**Comment by aprofeit** [comment]
Since https://github.com/activemerchant/active_merchant/commit/d91ccd7442cffd8cfb76013a3489c2e8a806ab6f this will now return `false` instead of erroring if there are spaces present in the number. You should still strip spaces from the number before passing it to this method since a valid number with a space will still return `false`. Example:
```
irb(main):001:0> ActiveMerchant::Billing::CreditCard.valid_number?("4242424242424242")
=> true
irb(main):002:0> ActiveMerchant::Billing::CreditCard.valid_number?("4242424242424242 ")
=> false
irb(main):003:0>
```
