### ISSUE TITLE
Authorize.net split_authorization Receives instance of CreditCard instead of String.

### ISSUE THREAD

**Issue by jimjeffers** [activemerchant/active_merchant#2008]
I've been banging my head on this strange bug causing my spec to fail. It looks like `/lib/active_merchant/billing/gateways/authorize_net.rb:749:in `split_authorization'` is receiving a credit card object instead of the '#' separated  string. Here's a full stack trace:

```
  1) Transaction#authorize When a correct credit card is passed to it errors 
     Failure/Error: self.gateway.capture(total, card)
     
     NoMethodError:
       undefined method `split' for #<ActiveMerchant::Billing::CreditCard:0x007fe8c0749400>
     # /Users/jim/.rvm/gems/ruby-2.3.0/gems/activemerchant-1.56.0/lib/active_merchant/billing/gateways/authorize_net.rb:749:in `split_authorization'
     # /Users/jim/.rvm/gems/ruby-2.3.0/gems/activemerchant-1.56.0/lib/active_merchant/billing/gateways/authorize_net.rb:772:in `auth_was_for_cim?'
     # /Users/jim/.rvm/gems/ruby-2.3.0/gems/activemerchant-1.56.0/lib/active_merchant/billing/gateways/authorize_net.rb:107:in `capture'
     # ./app/service_objects/transaction.rb:26:in `authorize'
     # ./spec/service_objects/transaction_spec.rb:41:in `block (5 levels) in <top (required)>'
     # /Users/jim/.rvm/gems/ruby-2.3.0/gems/vcr-3.0.1/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/jim/.rvm/gems/ruby-2.3.0/gems/vcr-3.0.1/lib/vcr.rb:189:in `use_cassette'
     # ./spec/service_objects/transaction_spec.rb:40:in `block (4 levels) in <top (required)>'
```

I've modified the source to output from AM using `pp`. 

**First, here is the output from `def commit(action, &payload)`:**

```
#<ActiveMerchant::Billing::Response:0x007fe8c3b952e0
   @authorization="2249806532#1111#purchase",
   @avs_result=
      {"code"=>"Y",
       "message"=>"Street address and 5-digit postal code match.",
       "street_match"=>"Y",
       "postal_match"=>"Y"},
   @cvv_result={"code"=>"P", "message"=>"CVV not processed"},
   @emv_authorization=nil,
   @error_code=nil,
   @fraud_review=false,
   @message="This transaction has been approved",
   @params=
      {"action"=>:purchase,
       "response_code"=>1,
       "response_reason_code"=>"1",
       "response_reason_text"=>"This transaction has been approved",
       "avs_result_code"=>"Y",
       "transaction_id"=>"2249806532",
       "card_code"=>"P",
       "authorization_code"=>"Y90ZU8",
       "cardholder_authentication_code"=>"2",
       "account_number"=>"1111",
       "test_request"=>"0"},
   @success=true,
   @test=true>
```

As far as I can tell everything is fine. Specifically the `@authorization="2249806532#1111#purchase",` looks appropriate. 

But then look what is happening here inside of `def split_authorization(authorization)`. When I output with `pp authorization` I get an instance of a CreditCard instead of the billing response's authorization string:

```
#<ActiveMerchant::Billing::CreditCard:0x007fe8c0749400
   @brand=nil,
   @first_name="Joe685",
   @last_name="Smith",
   @month=8,
   @number="4111111111111111",
   @verification_value=110,
   @year=2017>
```

Any idea why or what I may be doing wrong to cause this to happen. The raw response appears correct so my guess is something is getting botched inside of AM.

**Comment by jimjeffers** [comment]
Additional info:

I'm running Ruby 2.3 w/ ActiveMerchant 1.56.0

**Comment by jimjeffers** [comment]
After digging through the source of the actual project I inherited I realized it was our code calling capture incorrectly. Closing this ticket. Sorry about that.
