### ISSUE TITLE
Braintree Unit Tests Fail

### ISSUE THREAD

**Issue by bpollack** [activemerchant/active_merchant#2629]
When attempting to run the Braintree unit tests, there's a failure related to the logging level not being configured:

```
Failure: test_configured_logger_has_a_default_log_level_defined_by_active_merchant(BraintreeBlueTest)
/Users/benjamin/dev/active_merchant/test/unit/gateways/braintree_blue_test.rb:545:in `test_configured_logger_has_a_default_log_level_defined_by_active_merchant'
     542:   end
     543: 
     544:   def test_configured_logger_has_a_default_log_level_defined_by_active_merchant
  => 545:     assert_equal Logger::WARN, @internal_gateway.config.logger.level
     546:   end
     547: 
     548:   def test_default_logger_sets_warn_level_without_overwriting_global
<2> expected but was
<0>
===================================================================================================================================================================================
F
===================================================================================================================================================================================
Failure: test_default_logger_sets_warn_level_without_overwriting_global(BraintreeBlueTest)
/Users/benjamin/dev/active_merchant/test/unit/gateways/braintree_blue_test.rb:561:in `block in test_default_logger_sets_warn_level_without_overwriting_global'
     558:       )
     559:       internal_gateway = gateway.instance_variable_get(:@braintree_gateway)
     560: 
  => 561:       assert_equal Logger::WARN, internal_gateway.config.logger.level
     562:       assert_equal Logger::DEBUG, Braintree::Configuration.logger.level
     563:     end
     564:   end
/Users/benjamin/dev/active_merchant/test/unit/gateways/braintree_blue_test.rb:730:in `with_braintree_configuration_restoration'
/Users/benjamin/dev/active_merchant/test/unit/gateways/braintree_blue_test.rb:549:in `test_default_logger_sets_warn_level_without_overwriting_global'
<2> expected but was
<0>
```

This probably has no impact outside running the test suite, but it should probably be fixed.

**Comment by bpollack** [comment]
Hmm, no one else can repro this, so I'm going to assume it's an issue local to my machine; closing.
