### ISSUE TITLE
NoMethodError (undefined method `io' for nil:NilClass)

### ISSUE THREAD

**Issue by abarrak** [activemerchant/active_merchant#2882]
New changes in `net_http_ssl_connection.rb` brought some breakage on any service call to gateways for all of my usages ..

I wonder if anyone encountered such issue, and can point me on a possible fix.

Here's the log of error:

```
NoMethodError (undefined method `io' for nil:NilClass):
  
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/net_http_ssl_connection.rb:6:in `ssl_connection'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/connection.rb:78:in `block (2 levels) in request'
/Users/abdullah/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/connection.rb:76:in `block in request'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/network_connection_retries.rb:25:in `block in retry_exceptions'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/network_connection_retries.rb:48:in `retry_network_exceptions'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/network_connection_retries.rb:23:in `retry_exceptions'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/connection.rb:70:in `request'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/posts_data.rb:75:in `raw_ssl_request'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/posts_data.rb:45:in `ssl_request'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/billing/gateways/spreedly_core.rb:265:in `commit'
/Users/abdullah/.rvm/gems/ruby-2.4.1/bundler/gems/active_merchant/lib/active_merchant/billing/gateways/spreedly_core.rb:155:in `save_card'
```
```

**Comment by abarrak** [comment]
Fixed in PR: https://github.com/activemerchant/active_merchant/pull/2874.
